# Generated by Django 5.1.1 on 2024-09-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_electronico', models.EmailField(max_length=100, verbose_name='correo_electronico')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('asunto', models.TextField(max_length=400)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'Contacto_table',
            },
        ),
    ]
